name: Run Nifty Analysis

on:
  schedule:
    # Runs at 08:00 UTC on the 1st day of every month
    - cron: '0 12 * * *'
  workflow_dispatch: # Allows you to trigger it manually via the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          # We add yfinance and numpy here to support your script
          pip install pandas yfinance numpy
          python -m pip install --upgrade pip
          pip install gspread  # <--- Add all your required libraries here

      - name: Run Analysis Agent
        run: |
          # This command executes your script in the root directory
          python nifty_scanner.py
